// Mock result data for the multimodal search app
// Uses Unsplash stock photos that I know exist as thumbnail stand-ins.

const MOCK_RESULTS = [
  {
    id: 1,
    platform: "tiktok",
    handle: "@mayafromthefarm",
    caption: "the chicken who climbed a tree and refused to come down for 6 hours",
    views: "2.4M",
    likes: "412K",
    duration: "0:23",
    aspect: 0.75,
    thumb: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=600&q=80",
    matchReason: "chicken + tree + funny",
  },
  {
    id: 2,
    platform: "instagram",
    handle: "@poolpupsdaily",
    caption: "she sends it every single time. no fear in this household.",
    views: "884K",
    likes: "201K",
    duration: "0:14",
    aspect: 1.0,
    thumb: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=600&q=80",
    matchReason: "cat \u2022 water \u2022 jump",
  },
  {
    id: 3,
    platform: "tiktok",
    handle: "@nightlycafe",
    caption: "fairy lights + a small desk lamp = instant cozy. dorm tour pt. 4",
    views: "1.1M",
    likes: "189K",
    duration: "0:41",
    aspect: 1.33,
    thumb: "https://images.unsplash.com/photo-1522444195799-478538b28823?w=600&q=80",
    matchReason: "dorm \u2022 warm lighting",
  },
  {
    id: 4,
    platform: "instagram",
    handle: "@slow.sundays",
    caption: "pour-over morning, no phone, just the kettle",
    views: "322K",
    likes: "48K",
    duration: "0:18",
    aspect: 0.8,
    thumb: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600&q=80",
    matchReason: "slow morning vibe",
  },
  {
    id: 5,
    platform: "tiktok",
    handle: "@loveemusic",
    caption: "lovee meee \u2014 sped up version that's been stuck in my head all week",
    views: "5.8M",
    likes: "902K",
    duration: "0:29",
    aspect: 1.0,
    thumb: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=600&q=80",
    matchReason: "audio match \u2022 'love me'",
  },
  {
    id: 6,
    platform: "instagram",
    handle: "@studio.ivy",
    caption: "rearranged my bookshelf again. this is my roman empire.",
    views: "156K",
    likes: "22K",
    duration: "0:11",
    aspect: 1.25,
    thumb: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=600&q=80",
    matchReason: "cozy \u2022 interior",
  },
  {
    id: 7,
    platform: "tiktok",
    handle: "@benedictfarm",
    caption: "rooster on the roof AGAIN. third time this week",
    views: "743K",
    likes: "98K",
    duration: "0:09",
    aspect: 0.75,
    thumb: "https://images.unsplash.com/photo-1612170153139-6f881ff067e0?w=600&q=80",
    matchReason: "chicken + high place",
  },
  {
    id: 8,
    platform: "instagram",
    handle: "@kitchenlowlight",
    caption: "one pot pasta, one dim lamp, one very happy cat",
    views: "410K",
    likes: "67K",
    duration: "0:33",
    aspect: 1.0,
    thumb: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600&q=80",
    matchReason: "warm interior",
  },
  {
    id: 9,
    platform: "tiktok",
    handle: "@dailyfluff",
    caption: "cannonball technique: 10/10. splash radius: concerning.",
    views: "2.1M",
    likes: "351K",
    duration: "0:16",
    aspect: 0.85,
    thumb: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?w=600&q=80",
    matchReason: "cat \u2022 pool \u2022 jump",
  },
  {
    id: 10,
    platform: "tiktok",
    handle: "@folk.acoustic",
    caption: "covered 'lovee meee' on my porch last night, moths included",
    views: "612K",
    likes: "89K",
    duration: "0:52",
    aspect: 1.1,
    thumb: "https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=600&q=80",
    matchReason: "audio sim \u2022 92%",
  },
  {
    id: 11,
    platform: "instagram",
    handle: "@backyard.birds",
    caption: "okay but WHY is he up there. he doesn't even like heights.",
    views: "198K",
    likes: "31K",
    duration: "0:12",
    aspect: 1.15,
    thumb: "https://images.unsplash.com/photo-1569863959165-56dae551d4fc?w=600&q=80",
    matchReason: "chicken + tree",
  },
  {
    id: 12,
    platform: "tiktok",
    handle: "@tidyyy",
    caption: "reorganizing my desk drawer is my version of therapy",
    views: "889K",
    likes: "124K",
    duration: "0:38",
    aspect: 0.9,
    thumb: "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=600&q=80",
    matchReason: "cozy \u2022 desk",
  },
];

// Trending recent searches for empty state
const TRENDING = [
  "that chicken on a tree video",
  "cozy dorm fairy lights",
  "cat jumping into pool",
  "sped up lovee meee",
  "slow sunday morning coffee",
  "one pot pasta warm kitchen",
  "satisfying desk cleanup",
  "dog doing the thing",
];

const RECENT = [
  { q: "lovee meee sped up", mode: "audio", when: "2h ago" },
  { q: "cat jumping into pool", mode: "text", when: "yesterday" },
  { q: "Voice: 'that one recipe with miso'", mode: "voice", when: "2d ago" },
];

Object.assign(window, { MOCK_RESULTS, TRENDING, RECENT });
